from enum import StrEnum
from unicodedata import category

from pydantic import BaseModel, ConfigDict, Field

from review_agent.github import (
    ReviewComment,
    ReviewCommentGateway,
    derive_review_identity,
)
from review_agent.models import ReviewRequest, ReviewResult

GITHUB_COMMENT_MAX_BYTES = 65_536


class PublicationDisposition(StrEnum):
    CREATED = "created"
    UPDATED = "updated"
    ALREADY_CURRENT = "already_current"
    RECONCILED = "reconciled"


class PublicationReceipt(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    comment_id: int = Field(gt=0, strict=True)
    disposition: PublicationDisposition


class PublicationConsistencyError(Exception):
    """GitHub comment state cannot be resolved without operator intervention."""


def _longest_backtick_run(value: str) -> int:
    longest = 0
    current = 0
    for character in value:
        if character == "`":
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return longest


def _render_code_span(value: str) -> str:
    delimiter = "`" * (_longest_backtick_run(value) + 1)
    return f"{delimiter} {value} {delimiter}"


def _safe_model_text(value: str, *, declared_max: int) -> str:
    normalized = value.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    sanitized = "".join(
        " " if character == "\t" else "�" if category(character).startswith("C") else character
        for character in normalized
    )
    byte_budget = declared_max * 2 + 32
    rendered = _render_code_span(sanitized)
    if len(rendered.encode("utf-8")) <= byte_budget:
        return rendered

    marker = "… [truncated]"
    low = 0
    high = len(sanitized)
    while low < high:
        midpoint = (low + high + 1) // 2
        candidate = _render_code_span(f"{sanitized[:midpoint]}{marker}")
        if len(candidate.encode("utf-8")) <= byte_budget:
            low = midpoint
        else:
            high = midpoint - 1
    return _render_code_span(f"{sanitized[:low]}{marker}")


def render_review_comment(result: ReviewResult) -> str:
    lines = [
        "# Automated code review",
        "",
        "This comment was generated by the automated reviewer.",
        f"Reviewed commit range: `{result.diff_range.start_sha}..{result.diff_range.end_sha}`",
        "",
    ]
    if not result.findings:
        lines.extend(
            [
                "## No important issues found",
                "",
                "No blocking or important defects were found in this revision.",
            ]
        )
    else:
        lines.extend(["## Issues found", ""])
        for index, finding in enumerate(result.findings, start=1):
            lines.extend(
                [
                    f"### Finding {index}: {_safe_model_text(finding.title, declared_max=160)}",
                    "",
                    f"- Severity: {_safe_model_text(finding.severity, declared_max=9)}",
                    "- Locations:",
                ]
            )
            for location in finding.locations:
                line_suffix = f":{location.line}" if location.line is not None else ""
                rendered_location = _safe_model_text(
                    f"{location.path}{line_suffix}",
                    declared_max=524,
                )
                location_line = f"  - {rendered_location}"
                if location.description is not None:
                    location_line += (
                        f" — {_safe_model_text(location.description, declared_max=240)}"
                    )
                lines.append(location_line)
            lines.extend(
                [
                    f"- Evidence: {_safe_model_text(finding.evidence, declared_max=1_200)}",
                    f"- Impact: {_safe_model_text(finding.impact, declared_max=600)}",
                    (
                        "- Suggested fix: "
                        f"{_safe_model_text(finding.suggested_fix, declared_max=600)}"
                    ),
                    "",
                ]
            )

    comment = "\n".join(lines).rstrip() + "\n"
    if len(comment.encode("utf-8")) >= GITHUB_COMMENT_MAX_BYTES:
        msg = "valid review rendered above the GitHub comment limit"
        raise ValueError(msg)
    return comment


def _review_marker(request: ReviewRequest) -> str:
    identity = derive_review_identity(request)
    return f"<!-- {identity.external_id} -->"


def _expected_review_comment(request: ReviewRequest, result: ReviewResult) -> str:
    body = f"{render_review_comment(result)}\n{_review_marker(request)}\n"
    if len(body.encode("utf-8")) >= GITHUB_COMMENT_MAX_BYTES:
        msg = "valid review rendered above the GitHub comment limit"
        raise ValueError(msg)
    return body


def _validate_publication_input(request: ReviewRequest, result: ReviewResult) -> None:
    if (
        request.repository.lower() != result.repository.lower()
        or request.pr_number != result.pr_number
        or request.head_sha.lower() != result.diff_range.end_sha.lower()
    ):
        message = "review request and result identities do not match"
        raise ValueError(message)


def _is_owned_marker_comment(
    comment: ReviewComment,
    *,
    marker: str,
    app_id: int,
) -> bool:
    marker_line = f"\n{marker}\n"
    return (
        comment.body.endswith(marker_line)
        and comment.performed_via_github_app is not None
        and comment.performed_via_github_app.id == app_id
    )


def _confirmed_receipt(
    comment: ReviewComment,
    *,
    expected_body: str,
    app_id: int,
    disposition: PublicationDisposition,
) -> PublicationReceipt:
    marker = expected_body.splitlines()[-1]
    if (
        comment.body != expected_body
        or not _is_owned_marker_comment(comment, marker=marker, app_id=app_id)
    ):
        message = "GitHub did not confirm the expected application-owned review comment"
        raise PublicationConsistencyError(message)
    return PublicationReceipt(comment_id=comment.id, disposition=disposition)


def publish_review_result(
    *,
    request: ReviewRequest,
    result: ReviewResult,
    gateway: ReviewCommentGateway,
) -> PublicationReceipt:
    _validate_publication_input(request, result)
    expected_body = _expected_review_comment(request, result)
    marker = _review_marker(request)
    matches = tuple(
        comment
        for comment in gateway.list_review_comments(
            repository=request.repository,
            pr_number=request.pr_number,
            installation_id=request.installation_id,
        )
        if _is_owned_marker_comment(
            comment,
            marker=marker,
            app_id=gateway.app_id,
        )
    )
    if len(matches) == 1 and matches[0].body == expected_body:
        return PublicationReceipt(
            comment_id=matches[0].id,
            disposition=PublicationDisposition.ALREADY_CURRENT,
        )
    if len(matches) > 1:
        message = "multiple application-owned comments match the review revision"
        raise PublicationConsistencyError(message)
    if matches:
        updated = gateway.update_review_comment(
            repository=request.repository,
            comment_id=matches[0].id,
            installation_id=request.installation_id,
            body=expected_body,
        )
        return _confirmed_receipt(
            updated,
            expected_body=expected_body,
            app_id=gateway.app_id,
            disposition=PublicationDisposition.UPDATED,
        )
    created = gateway.create_review_comment(
        repository=request.repository,
        pr_number=request.pr_number,
        installation_id=request.installation_id,
        body=expected_body,
    )
    return _confirmed_receipt(
        created,
        expected_body=expected_body,
        app_id=gateway.app_id,
        disposition=PublicationDisposition.CREATED,
    )
