from typing import Protocol
from unicodedata import category

from review_agent.models import ReviewResult

GITHUB_COMMENT_MAX_BYTES = 65_536


class ReviewPublisher(Protocol):
    def publish(self, *, repository: str, pr_number: int, body: str) -> None: ...


def _longest_backtick_run(value: str) -> int:
    longest = 0
    current = 0
    for character in value:
        if character == "`":
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return longest


def _render_code_span(value: str) -> str:
    delimiter = "`" * (_longest_backtick_run(value) + 1)
    return f"{delimiter} {value} {delimiter}"


def _safe_model_text(value: str, *, declared_max: int) -> str:
    normalized = value.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    sanitized = "".join(
        " " if character == "\t" else "�" if category(character).startswith("C") else character
        for character in normalized
    )
    byte_budget = declared_max * 2 + 32
    rendered = _render_code_span(sanitized)
    if len(rendered.encode("utf-8")) <= byte_budget:
        return rendered

    marker = "… [truncated]"
    low = 0
    high = len(sanitized)
    while low < high:
        midpoint = (low + high + 1) // 2
        candidate = _render_code_span(f"{sanitized[:midpoint]}{marker}")
        if len(candidate.encode("utf-8")) <= byte_budget:
            low = midpoint
        else:
            high = midpoint - 1
    return _render_code_span(f"{sanitized[:low]}{marker}")


def render_review_comment(result: ReviewResult) -> str:
    lines = [
        "# Automated code review",
        "",
        "This comment was generated by the automated reviewer.",
        f"Reviewed commit range: `{result.diff_range.start_sha}..{result.diff_range.end_sha}`",
        "",
    ]
    if not result.findings:
        lines.extend(
            [
                "## No important issues found",
                "",
                "No blocking or important defects were found in this revision.",
            ]
        )
    else:
        lines.extend(["## Issues found", ""])
        for index, finding in enumerate(result.findings, start=1):
            lines.extend(
                [
                    f"### Finding {index}: {_safe_model_text(finding.title, declared_max=160)}",
                    "",
                    f"- Severity: {_safe_model_text(finding.severity, declared_max=9)}",
                    "- Locations:",
                ]
            )
            for location in finding.locations:
                line_suffix = f":{location.line}" if location.line is not None else ""
                rendered_location = _safe_model_text(
                    f"{location.path}{line_suffix}",
                    declared_max=524,
                )
                location_line = f"  - {rendered_location}"
                if location.description is not None:
                    location_line += (
                        f" — {_safe_model_text(location.description, declared_max=240)}"
                    )
                lines.append(location_line)
            lines.extend(
                [
                    f"- Evidence: {_safe_model_text(finding.evidence, declared_max=1_200)}",
                    f"- Impact: {_safe_model_text(finding.impact, declared_max=600)}",
                    (
                        "- Suggested fix: "
                        f"{_safe_model_text(finding.suggested_fix, declared_max=600)}"
                    ),
                    "",
                ]
            )

    comment = "\n".join(lines).rstrip() + "\n"
    if len(comment.encode("utf-8")) >= GITHUB_COMMENT_MAX_BYTES:
        msg = "valid review rendered above the GitHub comment limit"
        raise ValueError(msg)
    return comment


def publish_review_result(result: ReviewResult, publisher: ReviewPublisher) -> None:
    publisher.publish(
        repository=result.repository,
        pr_number=result.pr_number,
        body=render_review_comment(result),
    )
